### ISSUE TITLE
Three sets of dependencies

### ISSUE THREAD

**Issue by saulshanabrook** [shripalsoni04/nativescript-angular-web-starter#3]
What are the differences between the dependencies in `./package.json`, `./web/package.json`, and `./nativescript/package.json`? Do they have to contain the same versions? When adding a package, which one should it be added too?

**Comment by shripalsoni04** [comment]
Before answering your questions, let me describe some facts which will help you in understanding the answers.

`angular-cli` uses webpack during development and for preparing release builds for `web` project. While nativescript uses webpack only at the time of release/QA builds. It do not use webpack during development builds. Due to this difference, web project will be able to fetch dependencies from top `node_modules` folder but nativescript project will not be able to fetch it. So if you want to add any common dependencies like `lodash`, you need to add it at `nativescript/package.json` and `./package.json`.
 
Now, you may have question if web project can fetch dependencies from top level `node_modules` folder, why we have added `angular` dependencies at both `./package.json` and `./web/package.json`. This is because of issue with AOT as mentioned at Point 2 of [Known Issues](https://github.com/shripalsoni04/nativescript-angular-web-starter#known-issues-and-solution). Once that is resolved, we may remove any common dependency from `./web/package.json` and just maintain it at `./package.json`.

With this preface, let me now answer to your questions based on current scenario:
**1. Difference between `./package.json`, `./web/package.json` and `./nativescript/package.json`**

`package.json` - Generally contains common development dependencies and dependencies required by any code in `x-shared` folder.

`./web/package.json` - This contains all the dependencies required by web project.

`./nativescript/package.json` - This contains all the dependencies required by nativescript project.
 

**2. Do they have to contain same versions?**
No. You can keep the different version for `./web/package.json` and `./nativescript/package.json` projects. But keep the versions of common dependencies in `./web/package.json` and `./package.json` same. For example that of `angular`.

**3. When adding a package, which one should it be added to**
Its simple. If you execute `npm install <som_package>` at root level, it will be added to `./package.json`. If you execute that command from `./nativescript` folder, it will be added to `./nativescript/package.json` and if you execute that command from `./web` folder, it will be added to `./web/package,json`.

I think we should add a new commnad like `npm run shared-install <package_name>` or something, which will automatically install or update the package at both `./package.json` and `./nativescript/package.json`. Let me know if you have any suggestion for this.

Hope this will clarify your doubts.

**Comment by saulshanabrook** [comment]
@shripalsoni04 Thank you so much for that very thorough answer! I appreciate the work you have put into this project.
